version: '2'
services:
  metfamily1:
    image: metfamily-dev
    volumes:
      - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
    expose:
      - "3838"
  metfamily2:
    image: metfamily-dev
    volumes:
      - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
    expose:
      - "3838"
  metfamily3:
    image: metfamily-dev
    volumes:
      - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
    expose:
      - "3838"  
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "9080:80"
    links:
      - metfamily1
      - metfamily2
      - metfamily3

networks:
  default:
    driver: bridge
