version: '2'

services:
  metfamily:
    image: korseby/metfamily-dev
    networks:
    - metfamily-dev_net
    volumes:
    - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
    expose:
    - 3838

  haproxy:
    container_name: metfamily-dev_haproxy
    build: metfamily-haproxy
    networks:
    - metfamily-dev_net
    volumes:
    - ./metfamily-haproxy:/haproxy-override
    links:
    - korseby/metfamily-dev
    ports:
    - "9011:80"
    - "9012:70"
    expose:
    - "80"
    - "70"

networks:
  metfamily-dev_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.83.83.0/24
        ip_range: 10.83.83.0/24
        gateway: 10.83.83.1

