weba:
  #build: .
  image: metfamily-dev
  volumes:
  - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
  expose:
    - 3838

webb:
  #build: .
  image: metfamily-dev
  volumes:
  - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
  expose:
    - 3838

webc:
  #build: .
  image: metfamily-dev
  volumes:
  - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
  expose:
    - 3838

haproxy:
  image: haproxy
  volumes:
   - haproxy:/haproxy-override
  links:
   - weba
   - webb
   - webc
  ports:
   - "9080:80"
   - "9070:70"
  expose:
   - "80"
   - "70"

