apiVersion: v1
kind: ReplicationController
metadata:
  name: metfamily-rc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: metfamily
    spec:
      containers:
      - name: metfamily
        image: metfamily
        resources:
          limits:
            cpu: "0.1"
            memory: "4Gi"
        volumeMounts:
          - name: metfamily-path
            mountPath: "/vol/R/shiny/srv/shiny-server/MetFam"
            readOnly: true
          - name: metfamily-tmp
            mountPath: "/tmp"
            readOnly: false
        ports:
        - containerPort: 3838
      volumes:
        - name: metfamily-path
          hostPath:
            path: "/vol/R/shiny/srv/shiny-server/MetFam"
        - name: metfamily-tmp
          hostPath:
            path: "/tmp"
