apiVersion: v1
kind: Service
metadata:
  name: metfamily-service
  labels:
    app: metfamily
spec:
  selector:
    app: metfamily
  type: NodePort
  ports:
  - port: 9080
    targetPort: 3838
    protocol: TCP
  sessionAffinity: ClientIP
  clusterIP: 10.0.0.101
#  loadBalancerIP: 192.168.0.175
  externalIPs: [ "192.168.0.175" ]
#  type: LoadBalancer

